version: '2'

services:
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 && tail -f /dev/null
    volumes:
      - .:/code/app
    ports:
      - 8000:8000   # external : internal
